repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
        exclude: patch_dir
      - id: check-toml
      - id: end-of-file-fixer
        exclude: patch_dir
      - id: check-yaml
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.10.1
    hooks:
    - id: black
      pass_filenames: true
      exclude: _vendor|vendored|examples
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        exclude: _vendor|vendored
        args: [--output-format, github]
