repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-toml
      - id: end-of-file-fixer
      - id: check-yaml
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.7.0
    hooks:
    - id: black
      pass_filenames: true
      exclude: _vendor|vendored|examples
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.284
    hooks:
      - id: ruff
        exclude: _vendor|vendored
